name: CI/CD Pipeline

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:
      - dev, main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Input Validation
      run : |
        echo "Input Validation"
        echo "${{vars.GITHUB_ENV}}"

    - name: Checkout code
      uses: actions/checkout@v4

    # - name: Installing Workstation
    #   run: |
    #     wget https://packages.chef.io/files/stable/chef-workstation/23.12.1055/ubuntu/22.04/chef-workstation_23.12.1055-1_amd64.deb; sudo dpkg -i chef-workstation_23.12.1055-1_amd64.deb
    #     echo 'yes' | sudo chef env

    # - name: Fetch Dev branch
    #   run: git fetch origin dev:dev

    # - name: Metadata Check
    #   run: |
    #     git branch
    #     sudo chmod 777 .github/workflows/metadatacheck.sh
    #     sudo bash .github/workflows/metadatacheck.sh

    # - name: Linting Check
    #   run: cookstyle

    # - name: Kitchen
    #   run: | 
    #     kitchen verify
    #     kitchen destroy

    # - name: Policy Management
    #   run: | 
    #     sudo chmod 777 .github/workflows/policy_manage.sh
    #     sudo ./.github/workflows/policy_manage.sh "$ORG_DATA" "$CHEFADMIN" "$TESTUSER"
    #   env:
    #     ORG_DATA: ${{ vars.ORG_DETAILS }}
    #     CHEFADMIN: ${{ secrets.CHEFADMIN }}
    #     TESTUSER: ${{ secrets.TESTUSER }}
