name: CI/CD Pipeline

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: PR Test
      run: |
        echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        echo $GITHUB_HEAD_REF	
        echo $GITHUB_REF


    - name: Auto-Merge on PR Close
      if: github.event_name == 'pull_request' && github.event.pull_request.merged
      run: |
        # Replace 'main' with your target branch
        git checkout main
        gh pr merge ${{ github.event.pull_request.number }} --squash --auto
