name: CI/CD Pipeline

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: PR Test
      run: |
        echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        echo $GITHUB_HEAD_REF	
        echo $GITHUB_REF

    - name: Fetch Dev branch
      run: git fetch origin dev:dev

    - name: Set GH_TOKEN environment variable
      run: |
        echo "env:\n  GH_TOKEN: \${{ secrets.GH_TOKEN }}" > $GITHUB_ENV

    - name: Auto-Merge on PR Close
      if: github.event_name == 'pull_request'
      run: |
        # Replace 'main' with your target branch
        git checkout dev
        gh pr merge ${{ github.event.pull_request.number }} --squash --auto
