name: CI/CD Pipeline

# on:
#   push:
#     branches:
#       - dev

on:
  pull_request:
    types: [opened, edited]
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: justForTesting
      run: ls; pwd; tee

    - name: Checkout code
      uses: actions/checkout@v4

    # - name: Installing Workstation
    #   run: wget https://packages.chef.io/files/stable/chef-workstation/23.12.1055/ubuntu/22.04/chef-workstation_23.12.1055-1_amd64.deb; sudo dpkg -i chef-workstation_23.12.1055-1_amd64.deb

    - name: Workstation Setup
      run: |
        sudo pwd; sudo ls -a; sudo tree; sudo tree .github
        sudo chmod 777 .github/workflows/setup.sh
        sudo sh .github/workflows/setup.sh
        sudo mkdir -p ~/.chef
        sudo chmod 777 ~/.chef
        sudo ls -lhrt ~/.chef
        sudo echo "${{ secrets.CHEFADMIN_KEY }}" > ~/.chef/chefadmin.pem
        sudo cat ~/.chef/chefadmin.pem