name: CI/CD Pipeline

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-20.04
    env: 
      pat_token: ${{ secrets.GH_TOKEN }}
      parameter1: '42574587345'
      parameter2: 'TestStringWithoutSpace'
    steps:
    - name: Input Validation
      run : |
        echo "Input Validation"

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Trigger the Workflow
      run: |
        python .github/workflows/triggerscripts.py ${{ env.pat_token }}  'ankit100ni-org'  'InvokeGitHubActionsCalled' 'CalledWorkflow' ${{ env.parameter1 }} ${{ env.parameter2 }}

    # - name: Calling Pipeline
    #   run: |
    #     TOKEN="${{ secrets.GH_TOKEN }}"
    #     OWNER="ankit100ni-org"
    #     REPO="base-policy"
    #     Workflow_Name="base"
    #     parameter1="value1"
    #     parameter2="value2"
        
    #     curl -X POST \
    #       -H "Accept: application/vnd.github.v3+json" \
    #       -H "Authorization: token $TOKEN" \
    #       -d "{\"event_type\": \"$Workflow_Name\", \"client_payload\": {\"parameter1\": \"$parameter1\", \"parameter2\": \"$parameter2\"}}" \
    #       "https://api.github.com/repos/$OWNER/$REPO/dispatches"
      

    # - name: Installing Workstation
    #   run: |
    #     wget https://packages.chef.io/files/stable/chef-workstation/23.12.1055/ubuntu/22.04/chef-workstation_23.12.1055-1_amd64.deb; sudo dpkg -i chef-workstation_23.12.1055-1_amd64.deb
    #     echo 'yes' | sudo chef env

    # - name: Fetch Dev branch
    #   run: git fetch origin dev:dev

    # - name: Metadata Check
    #   run: |
    #     git branch
    #     sudo chmod 777 .github/workflows/metadatacheck.sh
    #     sudo bash .github/workflows/metadatacheck.sh

    # - name: Linting Check
    #   run: cookstyle

    # - name: Kitchen
    #   run: | 
    #     kitchen verify
    #     kitchen destroy

    # - name: Policy Management
    #   run: | 
    #     sudo chmod 777 .github/workflows/policy_manage.sh
    #     sudo ./.github/workflows/policy_manage.sh "$ORG_DATA" "$CHEFADMIN" "$TESTUSER"
    #   env:
    #     ORG_DATA: ${{ vars.ORG_DETAILS }}
    #     CHEFADMIN: ${{ secrets.CHEFADMIN }}
    #     TESTUSER: ${{ secrets.TESTUSER }}
