name: CI/CD Pipeline

# on:
#   push:
#     branches:
#       - dev

on:
  pull_request:
    types: [opened, reopened, edited]
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: justForTesting
      run: ls; pwd; tee

    # - name: Installing Workstation
    #   run: wget https://packages.chef.io/files/stable/chef-workstation/23.12.1055/ubuntu/22.04/chef-workstation_23.12.1055-1_amd64.deb; sudo dpkg -i chef-workstation_23.12.1055-1_amd64.deb

    - name: Workstation Setup
      run: |
        sudo mkdir -p ~/.chef
        sudo tee cat ~/.chef/credentials > /dev/null <<EOT
        [default]
        client_name     = 'chefadmin'
        client_key      = '/Users/anksoni/.chef/chefadmin.pem'
        chef_server_url = 'https://@@@@server_fqdn@@@@/organizations/qa'
        EOT
        sudo cat ~/.chef/credentials
        sudo chmod 777 ~/.chef
        sudo ls -lhrt ~/.chef
        sudo echo "${{ secrets.CHEFADMIN_KEY }}" > ~/.chef/chefadmin.pem
        sudo ls -lhrt ~/.chef/
        sudo cat ~/.chef/chefadmin.pem

