name: policy_push

on:
  workflow_run:
    workflows: ["CI/CD Pipeline"]
    types:
      - completed
    
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-20.04

    steps:
    - name: justForTesting
      run: ls; pwd; tee; docker -v
